---

- name: install httpd
  hosts: dbservers
  remote_user: ansible-user
  become: true

  tasks:

    - name: copy index.html file
      copy:
        src: /home/ansible-user/ansible_test/index.html
        dest: /home/ansible-user/my-project

    - name: install httpd
      yum:
        name: httpd
        state: latest

    - name: start httpd service on linux
      service:
        name: httpd
        state: started


      
